# export env vars
export BUN="$HOME/.bun/bin"
export PUB="$HOME/.pub-cache/bin"
export RAILS_NEW="$HOME/rails-new"

# add the exports above to PATH
export PATH="$BUN:$FLUTTER:$PUB:$RAILS_NEW:$PATH"

# lazy load the zsh promptinit function in normal mode
autoload -U promptinit

# initialize the zshell prompt system
promptinit

# custom zsh prompt
PROMPT=$'%B%n%b %F{yellow}\U222B '
RPROMPT=$'%F{green}%T %F{red}\U2665 %F{blue}%d'

# aliases
alias find="fd"
alias cat="bat --theme=\"Catppuccin Frappe\""
alias ls="eza --icons=always"
alias lsl="ls -l"
alias lsls="lsl --total-size"
alias bench="hyperfine"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/al/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/al/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/al/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/al/google-cloud-sdk/completion.zsh.inc'; fi

# enable zsh syntax highlighting 
source $HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# bun completions
[ -s "/Users/al/.bun/_bun" ] && source "/Users/al/.bun/_bun"

# run zellij on shell startup
eval "$(zellij setup --generate-auto-start zsh)"
